#! /bin/bash
blktrace -d /dev/sdb -o qq &
filebench -f $1
kill -2 `ps -aux | grep blktrace | head -n1 | awk '{print $2}'`
wait # block shell process,waiting all the subprocess generated by it to run to here, i.e., synchronous
blkparse -i qq -d qq.out
btt -i qq.out -B qq_off
echo "end2"
exit 0
